#!/usr/bin/env bash

error_log="/var/log/apache2/error.log"

# check for 4xx errors and output to the screen
echo "4xx errors:"

if ! sudo egrep '\s4[0-9]{2}\s' "$error_log";
then
        echo "Not found"
fi

# check for 5xx errors and output to the screen
echo "5xx errors:"

if ! sudo egrep '\s5[0-9]{2}\s' "$error_log";
then
        echo "Not found"
fi
